version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: 3
        INSTALL_NODE: "false"
        NODE_VERSION: "lts/*"
        USER_UID: 1000
        USER_GID: 1000
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    user: vscode
  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  querys:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        VARIANT: 3
    deploy:
      replicas: 3
    ports:
      - 8000
    command: python main.py